/**
 * Embeds the profile corpus once, at authoring time.
 *
 *   npm run embed:profile
 *
 * Fifteen passages do not justify a database. The vectors are written to
 * `data/profile-corpus.json` and committed, so the deployed site needs no
 * migration, no seed step and no query round trip to answer a question about
 * its author. Retrieval is a dot product over an array held in memory.
 *
 * The trade is that editing `content/profile.ts` without re-running this leaves
 * the corpus stale. The route refuses to start if the two disagree, so that
 * fails loudly rather than silently answering from old text.
 */

import { createHash } from "node:crypto";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

import "./lib/env";
import { PROFILE_DOCS } from "../content/profile";
import { embed } from "../lib/ai/openai";
import { sourceHash } from "../lib/profile/hash";

const OUT_DIR = join(process.cwd(), "data");
const OUT_PATH = join(OUT_DIR, "profile-corpus.json");

async function main() {
  console.log(`Embedding ${PROFILE_DOCS.length} profile passages…`);

  const { vectors, usage } = await embed(PROFILE_DOCS.map((doc) => `${doc.title}\n\n${doc.text}`));

  const entries = PROFILE_DOCS.map((doc, index) => ({
    ref: doc.ref,
    title: doc.title,
    text: doc.text,
    embedding: vectors[index],
  }));

  const payload = {
    $comment:
      "Generated by scripts/embed-profile.ts. Edit content/profile.ts and re-run npm run embed:profile.",
    model: usage.model,
    sourceHash: sourceHash(PROFILE_DOCS),
    dimensions: vectors[0]?.length ?? 0,
    entries,
  };

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_PATH, `${JSON.stringify(payload, null, 1)}\n`, "utf8");

  const bytes = Buffer.byteLength(JSON.stringify(payload));
  console.log(
    `Wrote ${entries.length} passages to data/profile-corpus.json ` +
      `(${(bytes / 1024).toFixed(0)} KB, ${payload.dimensions} dims, ` +
      `${usage.inputTokens} tokens, sha ${payload.sourceHash.slice(0, 12)})`,
  );

  // Printed so a reviewer can see the corpus is small enough that in-memory
  // retrieval is obviously the right call rather than a shortcut.
  const longest = PROFILE_DOCS.reduce((max, d) => Math.max(max, d.text.length), 0);
  console.log(`Longest passage: ${longest} characters.`);
  void createHash;
}

main().catch((cause) => {
  console.error(cause);
  process.exit(1);
});
