/**
 * Embeds the golden queries once, so the profile retrieval test needs no API
 * key.
 *
 *   npm run embed:profile:eval
 *
 * Same bargain as the corpus itself. A test that costs money and needs a
 * secret is a test that stops being run, and this one only has to check that
 * fixed vectors still rank the way they did.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { readFile } from "node:fs/promises";

import "./lib/env";
import { embed } from "../lib/ai/openai";

const CASES_PATH = join(process.cwd(), "evals", "cases", "profile.json");
const OUT_PATH = join(process.cwd(), "evals", "cases", "profile-vectors.json");

/** Mirrors the unrelated list in `evals/profile.eval.test.ts`. */
const UNRELATED = [
  "What is the capital of France?",
  "Write me a poem about the sea",
  "Explain how a diesel engine works",
  "Does he have children?",
  "What did he have for breakfast?",
];

async function main() {
  const golden = JSON.parse(await readFile(CASES_PATH, "utf8")) as {
    inCorpus: { query: string }[];
    offCorpus: { query: string }[];
  };

  const queries = [
    ...golden.inCorpus.map((c) => c.query),
    ...golden.offCorpus.map((c) => c.query),
    ...UNRELATED,
  ].filter((query, index, all) => all.indexOf(query) === index);

  console.log(`Embedding ${queries.length} golden queries…`);
  const { vectors: embedded } = await embed(queries);

  const vectors: Record<string, number[]> = {};
  queries.forEach((query, index) => {
    vectors[query] = embedded[index];
  });

  await writeFile(
    OUT_PATH,
    `${JSON.stringify({ $comment: "Generated by scripts/embed-profile-queries.ts.", vectors }, null, 1)}\n`,
    "utf8",
  );
  console.log(`Wrote ${queries.length} query vectors to evals/cases/profile-vectors.json`);
}

main().catch((cause) => {
  console.error(cause);
  process.exit(1);
});
